### ISSUE TITLE
Bad Network-Config after create/start of container (docker 1.2)

### ISSUE THREAD

**Issue by jarmoni** [floto/floto#19]
#### Issue
* Host-networking is not activated when executing the current code (master-branch)

#### But
* Run a container via terminal (--net="host") works fine
* Posting the JSON-body produced from terminal-client fails if executed with floto (master-branch)
* Posting the JSON-body produced from terminal-client is successful when executed with curl
* Posting the JSON-body produced from terminal-client is successful when executed with floto (branch: network_issue)

The solution of branch *network_issue* just proves that the API-calls work and we have to fix the issue on our side

**Comment by manuel-woelker** [comment]
Confirmed working in docker 1.4
