### ISSUE TITLE
addTemplate() create files with last modified date 01.01.1970

### ISSUE THREAD

**Issue by harald-k** [floto/floto#50]
Files which copied with with the addTemplate() function to the docker container has the last modified date 01.01.1970. This can cause several problems, if an application use this date.

Sample:
```
$ stat test.txt
  File: './test.txt'
  Size: 89              Blocks: 8          IO Block: 4096   regular file
Device: 3ch/60d Inode: 60          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-01-01 00:00:00.000000000 +0000
Modify: 1970-01-01 00:00:00.000000000 +0000
Change: 2016-03-22 09:24:09.239482349 +0000
 Birth: -
```

**Comment by manuel-woelker** [comment]
Unfortunately this is a workaround that is necessary to ensure that the docker caching mechanism works.

If a specific (or newer) last modified date is required, please use touch or touch -mt to explicitly set the date.
